[SQUASH] Remove SystemUI-related commits causing issues
Revert "[DO NOT MERGE] VibratorService: bypass AppOps check"

* Causes "Operation not started: uid=10324 pkg=com.android.systemui(null) op=VIBRATE" log spam.

This reverts commit 69e0ee1d0cd9825a60765a2a35581344315e58c5.

Revert "FODCircleView: Ignore assistant UI when showing bouncer"

This reverts commit 9ffac95356c3d3aec156a93c35048b231cbdd64e.

Revert "FODCircleView: Don't show on top of assistant UI"

"Caught a RuntimeException from the binder stub implementation.
java.lang.NullPointerException: Attempt to read from field 'boolean android.app.ActivityManager$StackInfo.visible' on a null object reference
	at com.android.systemui.biometrics.FODCircleView$3.onTaskStackChangedBackground(FODCircleView.java:326)
	at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:101)
	at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:403)
	at android.os.Binder.execTransactInternal(Binder.java:1159)
	at android.os.Binder.execTransact(Binder.java:1123)"

This reverts commit e59b0228c87730c10803f2697dcbdbd9f8656deb.